### ISSUE TITLE
Find graph library for payment overview

### ISSUE THREAD

**Issue by ReDMapLe024** [MooseLight/mortgage#4]
Edit (by Tyler):
- [x] Add sample graph page as a test
- [x] Fix sizing
- [x] Change it to a double bar graph for mortgage remaining and interest paid
- [x] Add meaningful data from mortgage calculator

**Comment by jasstsg** [comment]
Maybe this: https://www.chartjs.org/

**Comment by Tylernol2** [comment]
- [ ] Add sample graph page as a test
- [ ] Add meaningful data from mortgage calculator
